[package]
name = "lonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
envy = "0.4.2"
tokio = { version = "~1.17.0", features = ["full"] }
validators = "0.24.1"
warp = "0.3.2"
